### ISSUE TITLE
Epiviz broken in Firefox and Safari, not Chrome

### ISSUE THREAD

**Issue by dolleyj** [epiviz/epiviz.github.io#1]
@jkanche,  

The gEAR site does not work in Firefox and Safari, though it works in Chrome. I found that the site works if I disable the following links: 
```html
<script src="https://epiviz.github.io/polymer/charts/components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="https://epiviz.github.io/polymer/epiviz-v0.1.html">
```

**Comment by jkanche** [comment]
@dolleyj,

I can't access devel.umgear.org, is it still up and running ? If not can you spin it up so that i can see what the errors are ?

**Comment by dolleyj** [comment]
I started it back up. You should be able to access it now.

**Comment by jkanche** [comment]
@dolleyj,

This is because of a jquery conflict between epiviz and gear. i'll build a version of epiviz without jquery and see how it works.

**Comment by dolleyj** [comment]
Okay, thank you for the update.

**Comment by jkanche** [comment]
@dolleyj,

Can you use the following - 

```
<script src="https://epiviz.github.io/polymer/charts/components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="https://epiviz.github.io/polymer/epiviz-charts-v0.1-no-jquery.html">
```

Please add these import scripts after jquery.

**Comment by dolleyj** [comment]
Sorry for the delayed response.

I tried Epiviz in Chrome and FireFox. I get 404 on these two files:
https://epiviz.github.io/polymer/bower_components/polymer/lib/elements/dom-if.html
https://epiviz.github.io/polymer/bower_components/polymer/lib/elements/dom-repeat.html

**Comment by jkanche** [comment]
that is because of a bug one of the polymer packages i use. I did raise an issue and was going to be fixed in the next version. otherwise, do the charts load properly ?

**Comment by dolleyj** [comment]
They still aren't loading, but we are trying to pull the gene infomation json from 
http://epiviz-dev.cbcb.umd.edu/data2/main.php?action=search&q={gene_symbol}

Is this the lookup url we should be using? I get a 500 response.

**Comment by jkanche** [comment]
our dev server is currently in the process of a migration. Please use this instead

http://epiviz.cbcb.umd.edu/data2/main.php?action=search&q={gene_symbol}

Is gear-devel still up and running ?

**Comment by dolleyj** [comment]
Thanks! I can get the json now.

The charts are still not loading. I have a 404 on these 2 files, which yields more errors where multiple properties are undefined
https://epiviz.github.io/polymer/bower_components/polymer/lib/elements/dom-if.html
https://epiviz.github.io/polymer/bower_components/polymer/lib/elements/dom-repeat.html

![image](https://user-images.githubusercontent.com/6271039/30813701-223c17dc-a1dc-11e7-9dd2-a5af6f9e9c1c.png)

**Comment by dolleyj** [comment]
@jkanche, have you had a chance to look at this?

**Comment by jkanche** [comment]
@dolleyj 

Let me know if this works - 

```
<script src="https://epiviz.github.io/polymer/charts/components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="https://epiviz.github.io/polymer/epiviz-charts-v0.2-no-jquery.html">
```

Also are you on hangouts, so that we can fix this quickly ?

**Comment by jkanche** [comment]
@dolleyj 
Let me know if you run into any issues.
